apiVersion: apps/v1
kind: Deployment
metadata:
  name: jotterwebsite
  labels:
    app: jotterwebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jotterwebsite
  template:
    metadata:
      labels:
        app: jotterwebsite
    spec:
      imagePullSecrets:
        - name: acr-secret-jotterwebsite
      containers:
        - name: podinfo
          image: myregistry.azurecr.io/jotterwebsite:latest
          ports:
            - containerPort: 9898
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-acr-jotterwebsite"
