apiVersion: apps/v1
kind: Deployment
metadata:
  name: jotterwebsite
  labels:
    app: jotterwebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jotterwebsite
  template:
    metadata:
      labels:
        app: jotterwebsite
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.5.4
          ports:
            - containerPort: 9898
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
