apiVersion: v1
kind: Service
metadata:
  name: jotterwebsite
  labels:
    app: jotterwebsite
spec:
  type: ClusterIP
  selector:
    app: jotterwebsite
  ports:
    - port: 9898
      targetPort: 9898
      protocol: TCP
