apiVersion: v1
kind: Service
metadata:
  name: servicetest
  labels:
    app: servicetest
spec:
  type: ClusterIP
  selector:
    app: servicetest
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
