apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - ../../base/servicetest
  - ../../base/jotterwebsite

commonLabels:
  env: prod

patches:
  - target:
      kind: HelmRelease
      name: servicetest
    patch: |-
      - op: replace
        path: /spec/values/replicaCount
        value: 2
  - target:
      kind: Deployment
      name: jotterwebsite
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
