apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - namespace.yaml
  - ../../base/app1
  - ../../base/app2

commonLabels:
  env: prod

patches:
  - target:
      kind: Deployment
      name: app1
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: app2
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
